import '@/styles/globals.css'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import type { AppProps } from 'next/app'

import AOS from 'aos';
import { useEffect } from 'react';
import 'aos/dist/aos.css';


export default function App({ Component, pageProps }: AppProps) {

  useEffect(() => {
    AOS.init({
      startEvent: 'DOMContentLoaded', 
      initClassName: 'aos-init',
      animatedClassName: 'aos-animate'
    })
}, [])


  return (
    <>
      <Head>
          <title>Newva Capital</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>
      <Navbar/>
      <Component {...pageProps} />
    </>
  )
}
